/**
 * @capturelock/core
 *
 * Domain model, deterministic primitives, and the ports every outer layer
 * implements. This package has no dependency on Fastify, Drizzle, or any
 * payment provider, and nothing in it performs I/O.
 */

export type { Brand } from './brand.js';

export {
  CaptureLockError,
  CanonicalizationError,
  InvariantViolation,
  assertNever,
  type CaptureLockErrorCode,
} from './errors.js';

export {
  canonicalize,
  hash,
  hashBytes,
  asSha256Hex,
  isSha256Hex,
  HASH_DOMAINS,
  type HashDomain,
  type Sha256Hex,
} from './canonical.js';

export {
  CURRENCY_CODES,
  CURRENCY_EXPONENTS,
  CurrencyCodeSchema,
  CurrencyMismatchError,
  MAX_AMOUNT_MINOR,
  MoneyRangeError,
  MoneySchema,
  absolute,
  add,
  applyBasisPoints,
  compare,
  equals,
  format,
  isAtMost,
  isGreaterThan,
  isLessThan,
  isNegative,
  money,
  multiply,
  subtract,
  sum,
  zero,
  type CurrencyCode,
  type Money,
} from './money.js';

export {
  FixedClock,
  TimestampSchema,
  addMillis,
  addSeconds,
  asTimestamp,
  isAfter,
  isBefore,
  isTimestamp,
  millisBetween,
  systemClock,
  timestampFromDate,
  timestampToEpochMillis,
  type Clock,
  type Timestamp,
} from './time.js';

export {
  AuthorizationIdSchema,
  ChainIdSchema,
  EnvelopeIdSchema,
  EvaluationIdSchema,
  ID_PREFIXES,
  IdempotencyKeySchema,
  MAX_RECEIPT_LENGTH,
  MerchantIdSchema,
  ReceiptSchema,
  ReleaseIdSchema,
  RequestIdSchema,
  ReviewIdSchema,
  SessionIdSchema,
  SkuSchema,
  SnapshotIdSchema,
  UserIdSchema,
  asAuthorizationId,
  asChainId,
  asEnvelopeId,
  asReleaseId,
  asReviewId,
  asSessionId,
  asSnapshotId,
  deriveReceipt,
  newAuthorizationId,
  newChainId,
  newEnvelopeId,
  newEvaluationId,
  newReleaseId,
  newRequestId,
  newReviewId,
  newSessionId,
  newSnapshotId,
  type AuthorizationId,
  type ChainId,
  type EnvelopeId,
  type EvaluationId,
  type IdKind,
  type IdempotencyKey,
  type MerchantId,
  type Receipt,
  type ReleaseId,
  type RequestId,
  type ReviewId,
  type SessionId,
  type Sku,
  type SnapshotId,
  type UserId,
} from './ids.js';

export {
  REASON_CODES,
  REASON_CODE_DEFINITIONS,
  SEVERITY_RANK,
  isReasonCode,
  reasonDescription,
  reasonSeverity,
  reasonStage,
  type ReasonCode,
  type ReasonStage,
  type Severity,
} from './reason-codes.js';

export {
  AttributeListSchema,
  AttributePredicateSchema,
  AttributeSchema,
  findAttributeValues,
  hasAttribute,
  normalizeAttributes,
  satisfiesPredicate,
  type Attribute,
  type AttributePredicate,
} from './domain/attributes.js';

export {
  AuthorizationStateSchema,
  AuthorizedIntentSchema,
  FeeConstraintsSchema,
  GeographyConstraintSchema,
  IntentConstraintsSchema,
  IntentNormalizationMethodSchema,
  IntentNormalizationSchema,
  MerchantConstraintSchema,
  QuantityBandSchema,
  RecurrenceConstraintSchema,
  intentHashInput,
  type AuthorizationRecord,
  type AuthorizationState,
  type AuthorizedIntent,
  type FeeConstraints,
  type GeographyConstraint,
  type IntentConstraints,
  type IntentNormalization,
  type IntentNormalizationMethod,
  type MerchantConstraint,
  type QuantityBand,
  type RecurrenceConstraint,
} from './domain/intent.js';

export {
  AdjustmentTypeSchema,
  AgentAssertionSchema,
  CartAdjustmentSchema,
  CartLineSchema,
  FEE_ADJUSTMENT_TYPES,
  MAX_CART_ADJUSTMENTS,
  MAX_CART_LINES,
  ProposedCartSchema,
  ShipToSchema,
  cartHashInput,
  computeCartTotals,
  isFeeAdjustment,
  type AdjustmentType,
  type AgentAssertion,
  type CartAdjustment,
  type CartLine,
  type CartTotals,
  type ProposedCart,
  type ShipTo,
} from './domain/cart.js';

export {
  liveItemHashInput,
  liveItemRowHash,
  liveStateDigest,
  type LiveFeeQuote,
  type LiveItemState,
  type LiveMerchantState,
  type LiveStateResult,
} from './domain/live-state.js';

export {
  PurchaseSettlementStateSchema,
  SessionAuthorityStateSchema,
  SessionBoundsSchema,
  computeSessionBoundsHash,
  derivePurchaseRequestId,
  purchaseCeiling,
  remainingBudget,
  sessionBoundsHashInput,
  verifySessionBoundsIntegrity,
  type PurchaseSettlementState,
  type SessionAuthorityRecord,
  type SessionAuthorityState,
  type SessionBounds,
  type SessionPurchaseRecord,
} from './domain/session.js';

export {
  SnapshotStateSchema,
  computeSnapshotHash,
  snapshotHashInput,
  snapshotTotalsAreSelfConsistent,
  verifySnapshotIntegrity,
  type SnapshotState,
  type VerifiedSnapshot,
} from './domain/snapshot.js';

export {
  STAGE_IDS,
  compareFindings,
  computeDecisionHash,
  decisionHashInput,
  finding,
  type Finding,
  type FindingDetail,
  type FindingDetailValue,
  type Gate,
  type StageId,
  type StageReport,
  type StageStatus,
  type VerificationDecision,
  type Verdict,
} from './domain/decision.js';

export {
  INDETERMINATE_RELEASE_STATES,
  OPERATOR_ATTENTION_RELEASE_STATES,
  RELEASE_STATES,
  ReleaseStateSchema,
  TERMINAL_RELEASE_STATES,
  TRANSIENT_RELEASE_STATES,
  isTerminalReleaseState,
  isTransientReleaseState,
  moneyHasMoved,
  requiresOperatorAttention,
  requiresReconciliation,
  type ReleaseRecord,
  type ReleaseState,
} from './domain/release.js';

export type {
  CaptureOutcome,
  CapturePaymentRequest,
  PaymentExecutor,
  PaymentReader,
  CreateOrderOutcome,
  CreateOrderRequest,
  PaymentProvider,
  ProviderIndeterminateCause,
  ProviderOrder,
  ProviderOrderStatus,
  ProviderPayment,
  ProviderPaymentStatus,
  WebhookVerificationResult,
  WebhookVerifier,
} from './ports/payment-provider.js';

export type { FeeQuoteRequest, MerchantStateProvider } from './ports/merchant.js';

export type {
  AuthorizationRepository,
  EvaluationRecord,
  EvaluationRepository,
  InsertReleaseResult,
  RecordPurchaseResult,
  ReleaseRepository,
  ReleaseTransitionPatch,
  ReserveBudgetResult,
  ReviewRecord,
  ReviewRepository,
  ReviewState,
  SessionAuthorityRepository,
  SnapshotRepository,
  WebhookClaimResult,
  WebhookInboxRecord,
  WebhookInboxRepository,
  WebhookInboxStatus,
} from './ports/repositories.js';
